### PR TITLE
connects but might not close proprly

### LINKED ISSUE #26: How about upgrade lucas-clemente/quic-go to v0.14.0
I see currently we used quic-go's version is v0.7.1-0.20190401152353-907071221cf9, how about upgrading it to the latest release version.

### PR DESCRIPTION
**Pull request by cryptix**
closes #8, was missing NextProtos on tls.Config and context's.

quic.Config AcceptCookie seems to be gone but not really used anyhow?

quic.Session.Close is also gone. seems like it _should_ be some where but i couldn't find it just yet.

also fixes #26

TODO:
* [ ] read loop doesn't get unblocked
* [x] fix close handling of streams (166a0ed)
* [ ] fix nil panic in pion/webrtc E2E test because b.log isn't initialized (4315de1)

### CODE REVIEW

**Comment by Sean-Der** [comment]
Holy crap, this is amazing @cryptix thank you so much! This has been on my bucket list for a while :)

Are you using the QUIC ORTC stuff in `pion/webrtc`?

**Comment by Sean-Der** [comment]
I still need to setup ssb, I have this giant TODO list :( 

There is always a fire with Pion that keeps me from taking a day off to get into scuttlebutt properly

**Comment by cryptix** [comment]
@Sean-Der very welcome :)

> Are you using the QUIC ORTC stuff in pion/webrtc?

no, but i wanted try that next actually :D 

I'd also help with https://github.com/pion/quic/pull/28#issuecomment-626290950 if that could increase the test coverage. This one e2e test seems a bit weak.

>  I have this giant TODO list ... 

no worries, been there.. :)

**Comment by cryptix** [comment]
Hrm... I tried this branch with https://github.com/pion/webrtc/tree/master/examples/ortc-quic but I'm getting this unfortunate crash:

```

```

I might be using the example tool wrong. I start it twice, once with -offer and then past the base64 blobs into the others stdin, right?

**Comment by cryptix** [comment]
I just got `pion/webrtc/examples/ortc-quic` working. I had to fix up passing the established addresses around after ICE (otherwise quic's multiplexer is just confused and might even panic). Will polish up the patches next time.

**Comment by Sean-Der** [comment]
@cryptix :fire: that is amazing news!

I need to write docs for `ortc-quic` today. Mind if I add you to the Pion organization so you can review/approve my work around this? It will be way easier to collaborate.

I really want to support your work on this/unblock you as much as possible. It would be a shame to lose someone with enthusiasm in this area. I really need help on the QUIC stuff.

thanks

**Comment by cryptix** [comment]
> Mind if I add you to the Pion organization

Not at all :)

**Comment by cryptix** [comment]
closing in favor of #32 to allow contributer access to the branch.

**Pull request closed without merging**
